# Iris Dataset 

### Importação dos dados

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()


### Observações

In [4]:
x = iris.data

print(iris.data)  #cada um das linhas é uma amostra, então temos 150 amostras, compri_petala e larg_petada / compri_sepala e larg_sepala
#Isso parece uma lista  mas é um array numpy, muito usado em machine learning

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Target / Resultados


In [5]:
y = iris.target
print(iris.target) # no caso desse exemplo, o target são as espécies da planta
#para saber o nome das especies das plantas so usar o target_name

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Shapes das observações

In [6]:
print(iris.data.shape)  #Se tivessemos usando uma lista normal, poderiamos usar o len(), mas como é um array numpy não funciona
#no caso temos 150 observações(resultados) e 4 atributos(featcher)

(150, 4)


### Shapes dos target

In [7]:
print(iris.target.shape) # apenas o numero de resultados

(150,)


# Importação do KNN

#### O KNN é um modelo estatístico que vamos escolher para testar a performance
#### KNN (K Nearest neighbors) K vizinhos mais próximos.

In [8]:
from sklearn.neighbors import KNeighborsClassifier  #Importação da biblioteca
knn = KNeighborsClassifier(n_neighbors=1) #criamos uma variável para utilizar o KNN e definimos o valor de K vizinhos = 1

## Treinar a máquina

In [9]:
knn.fit(x, y)  # Rodado uma vez ele vai aprender e fazer os calculos de acordo com as informações já informadas pra ele

KNeighborsClassifier(n_neighbors=1)

## Fazer previsões

In [10]:
species = knn.predict([[5.9, 3,5.1, 1.8]])[0] # Ele vai fazer a previsão de acordo com o que ele aprendeu em knn.fit() 
print(iris.target_names[species])  #mostra o resultado da previsão dele

virginica


### Separar os dados em dois grupos

In [18]:
from sklearn.model_selection import train_test_split  #Precisamos de 2 variaveis x(iris.data) e 2 variaveis y(iris.target)
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size = 0.25) #Uma (x, y) para treinar e outra para testar
print(x_test.shape) #Vemos quantas foram usadas para teste              test_size= 0.25 ->é a porcentagem queele vai usar para treinar 

(38, 4)


### Avaliação da performance do modelo

In [12]:
knn.fit(x_train, y_train) #Ele vai aprender de acordo com os 25% definidos acima para o x e y de teste
previsoes = knn.predict(x_test) #previsoes feitas a partir do aprendizado do x e y de teste
print(previsoes)

[1 0 1 2 2 2 1 1 1 0 2 2 2 0 0 1 0 1 1 1 0 0 1 2 1 2 2 1 2 2 2 2 1 1 0 0 1
 0]


In [13]:
from sklearn import metrics  #calcular porcentagem de acertos
acertos = metrics.accuracy_score(y_test, previsoes)
print(acertos)

0.9736842105263158


## Aplicação do modelo de regressão logística

In [14]:
#É um  modelo de previsão logica, mais usada com a classificação binária
#exemplos:
#Se um email é ou não spam
#se um tumor é maligno ou benigno
#Mas pode ser usada tambem como mais de 2 parametros

##### Como ela preferêncialmente é usada com classificações binária, o eixo y dela é dividido em 0 e 1, com uma função que é calculada, vai definir uma curva em formato de S entre elas, e assim, de acordo com o valor do eixo X verifica uma certa porcentagem de ela ser ou não de um grupo. 

#### No caso das espécies de planta, que são 3 espécies, o algorítimo faz essa mesma conta pelo gráfico, e faz 3 gráficos na seguinte lógica, na porcentagem de ela ser(ser da espécie) ou não ser(2 espécies) da espécie. Então comparando o numero nos 3 gráficos das espécies de planta ele consegue achar a espécie.

In [19]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(x_train, y_train)
previsoes_logreg = logreg.predict(x_test)
acertos_logreg = metrics.accuracy_score(y_test, previsoes_logreg)
print(acertos_logreg)


0.9473684210526315
